on: push
name: Build and deploy GH Pages
jobs:
  build:
    runs-on: ubuntu-latest
    
    env:
      ZOLA_BUILD_DIR: 'public'
      
    steps:
      - name: checkout
        uses: actions/checkout@v2

      - name: Build site
        run: |
          sudo snap install zola --edge
          zola build -o $ZOLA_BUILD_DIR

      - name: Run theme post_build action
        run: |
          bash themes/zola-portfolio/post_build.sh $ZOLA_BUILD_DIR

      - name: Minify site
        run: |
          sudo apt update
          sudo apt install minify
          minify -r -v public/ -o public/

      - name: Commit minified changes
        run: |
          git config --local user.email "github-bot@noreply.github.com"
          git config --local user.name "Github Action"
          git commit -m "Minify output" -a

      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: 'gh-pages'
