on: push
name: Build and deploy GH Pages
jobs:
  build:
    runs-on: ubuntu-latest
    
    env:
      ZOLA_BUILD_DIR: 'public'
      
    steps:
      - name: checkout
        uses: actions/checkout@v2
        with:
          submodules: 'recursive'

      - name: Build site
        run: |
          sudo snap install zola --edge
          zola build -o $ZOLA_BUILD_DIR

      - name: Run theme post_build action
        run: |
          chmod + ./themes/zola-portfolio/post_build.sh
          ./themes/zola-portfolio/post_build.sh $ZOLA_BUILD_DIR

      - name: Minify site
        run: |
          sudo apt update
          sudo apt install minify
          minify -r -v $ZOLA_BUILD_DIR -o $ZOLA_BUILD_DIR
          
          - name: Deploy
            uses: peaceiris/actions-gh-pages@v3
            with:
              github_token: ${{ secrets.GITHUB_TOKEN }}
              publish_dir: ./public
